-- CreateTable (if not exists)
CREATE TABLE IF NOT EXISTS "FriendRequest" (
    "id" TEXT NOT NULL,
    "senderId" TEXT NOT NULL,
    "receiverId" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "FriendRequest_pkey" PRIMARY KEY ("id")
);

-- CreateTable (if not exists)
CREATE TABLE IF NOT EXISTS "AiPrompt" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AiPrompt_pkey" PRIMARY KEY ("id")
);

-- User table: add missing columns
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "themeIndex" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isRoyal" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rating" INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "rank" TEXT NOT NULL DEFAULT 'Novice';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "dailyWins" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "notesData" JSONB NOT NULL DEFAULT '{"nodes":[],"edges":[]}';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- Question table: add missing columns
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "problemId" INTEGER;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "idealComplexity" TEXT;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "timeLimit" INTEGER NOT NULL DEFAULT 5000;
ALTER TABLE "Question" ADD COLUMN IF NOT EXISTS "memoryLimit" INTEGER NOT NULL DEFAULT 256;

-- Duel table: add missing columns
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostFinalized" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestFinalized" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostComplexity" DOUBLE PRECISION;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestComplexity" DOUBLE PRECISION;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostPenalty" DOUBLE PRECISION;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestPenalty" DOUBLE PRECISION;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostRatingChange" INTEGER;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestRatingChange" INTEGER;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostCode" TEXT;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestCode" TEXT;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "finishReason" TEXT;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostCodeLength" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestCodeLength" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostLineCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestLineCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostTestsPassed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestTestsPassed" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostTestsTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestTestsTotal" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "hostLastActive" TIMESTAMP(3);
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "guestLastActive" TIMESTAMP(3);
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "startedAt" TIMESTAMP(3);
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "unrated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "gameMode" TEXT NOT NULL DEFAULT 'CODEKNIGHTS';
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "numProblems" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "totalTime" INTEGER NOT NULL DEFAULT 30;
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "difficulty" TEXT NOT NULL DEFAULT 'ANY';
ALTER TABLE "Duel" ADD COLUMN IF NOT EXISTS "questionIds" TEXT[] DEFAULT ARRAY[]::TEXT[];

-- CreateIndex (if not exists)
CREATE UNIQUE INDEX IF NOT EXISTS "FriendRequest_senderId_receiverId_key" ON "FriendRequest"("senderId", "receiverId");
CREATE UNIQUE INDEX IF NOT EXISTS "Question_problemId_key" ON "Question"("problemId");
CREATE UNIQUE INDEX IF NOT EXISTS "Question_title_key" ON "Question"("title");

-- AddForeignKey (with existence checks)
-- FriendRequest foreign keys
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FriendRequest_senderId_fkey') THEN
    ALTER TABLE "FriendRequest" ADD CONSTRAINT "FriendRequest_senderId_fkey" FOREIGN KEY ("senderId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FriendRequest_receiverId_fkey') THEN
    ALTER TABLE "FriendRequest" ADD CONSTRAINT "FriendRequest_receiverId_fkey" FOREIGN KEY ("receiverId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
END $$;

-- AiPrompt foreign key
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'AiPrompt_userId_fkey') THEN
    ALTER TABLE "AiPrompt" ADD CONSTRAINT "AiPrompt_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
  END IF;
END $$;

-- Update Duel hostId foreign key (was RESTRICT, now CASCADE)
DO $$ BEGIN
  IF EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Duel_hostId_fkey') THEN
    ALTER TABLE "Duel" DROP CONSTRAINT "Duel_hostId_fkey";
  END IF;
  ALTER TABLE "Duel" ADD CONSTRAINT "Duel_hostId_fkey" FOREIGN KEY ("hostId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
END $$;
