export const TRANSLATIONS = {
  en: {
    battle: "Battle", contests: "Contests", discuss: "Discuss", friends: "Friends", settings: "Settings", editor: "Editor", problem: "Problem", profile: "Profile", admin: "Dev Features", signIn: "Sign In", signOut: "Sign Out", exitGuest: "Exit Guest Mode", profileOverview: "Profile Overview", configureProfile: "Configure Profile", colorThemes: "Color Themes", fontFamily: "Font Family", textSize: "Text Size", keybindings: "Keybindings", language: "Interface Language", arenaRules: "Arena Rules", whyJoin: "Why Join?", authRequired: "Authentication Required", playAsGuest: "Play as Guest", startQuickBattle: "START QUICK BATTLE", availableChallenges: "Available Challenges", battleVictorious: "BATTLE VICTORIOUS", startNewBattle: "START NEW BATTLE", quitBattle: "Quit Battle?", quitWarning: "Your progress on this challenge will be lost. Are you sure you want to exit?", yesQuit: "YES, QUIT", cancel: "CANCEL", run: "RUN", testing: "TESTING...", runAllTests: "RUN ALL TESTS", runExample: "Run Example", addToStdin: "Add to Stdin", examples: "Examples", solvedProblems: "Solved Problems", winRate: "Win Rate", currentStreak: "Current Streak", battlesFought: "Battles Fought", battlesWon: "Battles Won", rank: "Rank", timeTaken: "Time Taken", langUsed: "Language", squire: "Squire", knight: "Knight", grandmaster: "Grandmaster", peasant: "Beginner Peasant",
  },
  ro: {
    battle: "Luptă", contests: "Concursuri", discuss: "Discuții", friends: "Prieteni", settings: "Setări", editor: "Editor", problem: "Problemă", profile: "Profil", admin: "Opțiuni Dev", signIn: "Autentificare", signOut: "Deconectare", exitGuest: "Ieșire Guest", profileOverview: "Privire de ansamblu", configureProfile: "Configurare Profil", colorThemes: "Teme Culori", fontFamily: "Font", textSize: "Mărime Text", keybindings: "Scurtături Tastatură", language: "Limba Interfeței", arenaRules: "Regulile Arenei", whyJoin: "De ce să te alături?", authRequired: "Autentificare Necesară", playAsGuest: "Joacă ca invitat", startQuickBattle: "START LUPTĂ RAPIDĂ", availableChallenges: "Provocări Disponibile", battleVictorious: "LUPTĂ CÂȘTIGATĂ", startNewBattle: "START LUPTĂ NOUĂ", quitBattle: "Părăsești lupta?", quitWarning: "Progresul tău la această provocare va fi pierdut. Sigur vrei să ieși?", yesQuit: "DA, IEȘI", cancel: "ANULEAZĂ", run: "EXECUTE", testing: "TESTARE...", runAllTests: "RULEAZĂ TOATE TESTELE", runExample: "Rulează Exemplul", addToStdin: "Adaugă la Stdin", examples: "Exemple", solvedProblems: "Probleme Rezolvate", winRate: "Rata de Câștig", currentStreak: "Serie curentă", battlesFought: "Lupte Date", battlesWon: "Lupte Câștigate", rank: "Rang", timeTaken: "Timp Necesar", langUsed: "Limbaj", squire: "Scutier", knight: "Cavaler", grandmaster: "Mare Maestru", peasant: "Țăran Începător",
  },
  fr: {
    battle: "Bataille", contests: "Concours", discuss: "Discuter", friends: "Amis", settings: "Paramètres", editor: "Éditeur", problem: "Problème", profile: "Profil", admin: "Options Dev", signIn: "Connexion", signOut: "Déconnexion", exitGuest: "Quitter Invité", profileOverview: "Aperçu du profil", configureProfile: "Configurer le profil", colorThemes: "Thèmes de couleur", fontFamily: "Police", textSize: "Taille du texte", keybindings: "Raccourcis", language: "Langue de l'interface", arenaRules: "Règles de l'arène", whyJoin: "Pourquoi rejoindre ?", authRequired: "Authentification requise", playAsGuest: "Jouer en tant qu'invité", startQuickBattle: "DÉMARRER BATAILLE RAPIDE", availableChallenges: "Défis disponibles", battleVictorious: "BATAILLE VICTORIEUSE", startNewBattle: "NOUVELLE BATAILLE", quitBattle: "Quitter la bataille ?", quitWarning: "Votre progression sera perdue. Voulez-vous vraiment quitter ?", yesQuit: "OUI, QUITTER", cancel: "ANNULER", run: "EXÉCUTER", testing: "TESTS...", runAllTests: "LANCER TOUS LES TESTS", runExample: "Lancer l'exemple", addToStdin: "Ajouter à Stdin", examples: "Exemples", solvedProblems: "Problèmes résolus", winRate: "Taux de victoire", currentStreak: "Série actuelle", battlesFought: "Batailles menées", battlesWon: "Batailles gagnées", rank: "Rang", timeTaken: "Temps pris", langUsed: "Langage", squire: "Écuyer", knight: "Chevalier", grandmaster: "Grand Maître", peasant: "Paysan débutant",
  },
  de: {
    battle: "Kampf", contests: "Wettbewerbe", discuss: "Diskussion", friends: "Freunde", settings: "Einstellungen", editor: "Editor", problem: "Problem", profile: "Profil", admin: "Dev-Funktionen", signIn: "Anmelden", signOut: "Abmelden", exitGuest: "Gastmodus verlassen", profileOverview: "Profilübersicht", configureProfile: "Profil konfigurieren", colorThemes: "Farbe", fontFamily: "Schriftart", textSize: "Textgröße", keybindings: "Tastenbelegung", language: "Oberflächensprache", arenaRules: "Arena-Regeln", whyJoin: "Warum beitreten?", authRequired: "Authentifizierung erforderlich", playAsGuest: "Als Gast spielen", startQuickBattle: "SCHNELLKAMPF STARTEN", availableChallenges: "Verfügbare Herausforderungen", battleVictorious: "KAMPF SIEGREICH", startNewBattle: "NEUER KAMPF", quitBattle: "Kampf verlassen?", quitWarning: "Ihr Fortschritt geht verloren. Möchten Sie wirklich beenden?", yesQuit: "JA, BEENDEN", cancel: "ABBRECHEN", run: "AUSFÜHREN", testing: "TESTEN...", runAllTests: "ALLE TESTS STARTEN", runExample: "Beispiel ausführen", addToStdin: "In Stdin einfügen", examples: "Beispiele", solvedProblems: "Gelöste Probleme", winRate: "Siegquote", currentStreak: "Aktuelle Serie", battlesFought: "Gekämpfte Schlachten", battlesWon: "Gewonnene Schlachten", rank: "Rang", timeTaken: "Zeitaufwand", langUsed: "Sprache", squire: "Knappe", knight: "Ritter", grandmaster: "Großmeister", peasant: "Anfänger Bauer",
  },
  hi: {
    battle: "युद्ध", contests: "प्रतियोगिताएं", discuss: "चर्चा", friends: "मित्र", settings: "सेटिंग्स", editor: "संपादक", problem: "समस्या", profile: "प्रोफ़ाइल", admin: "देव फीचर्स", signIn: "साइन इन", signOut: "साइन आउट", exitGuest: "अतिथि मोड से बाहर निकलें", profileOverview: "प्रोफ़ाइल अवलोकन", configureProfile: "प्रोफ़ाइल कॉन्फ़िगर करें", colorThemes: "रंग थीम", fontFamily: "फ़ॉन्ट परिवार", textSize: "टेक्स्ट आकार", keybindings: "कीबाइंडिंग", language: "इंटरफ़ेस भाषा", arenaRules: "अखाड़ा नियम", whyJoin: "क्यों जुड़ें?", authRequired: "प्रमाणीकरण आवश्यक", playAsGuest: "अतिथि के रूप में खेलें", startQuickBattle: "त्वरित युद्ध शुरू करें", availableChallenges: "उपलब्ध चुनौतियाँ", battleVictorious: "युद्ध विजयी", startNewBattle: "नया युद्ध शुरू करें", quitBattle: "युद्ध छोड़ें?", quitWarning: "आपकी प्रगति खो जाएगी। क्या आप वाकई बाहर निकलना चाहते हैं?", yesQuit: "हाँ, छोड़ें", cancel: "रद्द करें", run: "चलाएं", testing: "परीक्षण...", runAllTests: "सभी परीक्षण चलाएं", runExample: "उदाहरण चलाएं", addToStdin: "Stdin में जोड़ें", examples: "उदाहरण", solvedProblems: "हल की गई समस्याएं", winRate: "जीत की दर", currentStreak: "वर्तमान स्ट्रीक", battlesFought: "लड़े गए युद्ध", battlesWon: "जीते गए युद्ध", rank: "रैंक", timeTaken: "लिया गया समय", langUsed: "भाषा", squire: "स्क्वायर", knight: "नाइट", grandmaster: "ग्रैंडमास्टर", peasant: "शुरुआती किसान",
  },
  ru: {
    battle: "Битва", contests: "Конкурсы", discuss: "Обсуждение", friends: "Друзья", settings: "Настройки", editor: "Редактор", problem: "Задача", profile: "Профиль", admin: "Опции Dev", signIn: "Войти", signOut: "Выйти", exitGuest: "Выйти из режима гостя", profileOverview: "Обзор профиля", configureProfile: "Настроить профиль", colorThemes: "Цветовые темы", fontFamily: "Шрифт", textSize: "Размер текста", keybindings: "Горячие клавиши", language: "Язык интерфейса", arenaRules: "Правила арены", whyJoin: "Зачем вступать?", authRequired: "Требуется авторизация", playAsGuest: "Играть как гость", startQuickBattle: "НАЧАТЬ БЫСТРУЮ БИТВУ", availableChallenges: "Доступные задачи", battleVictorious: "ПОБЕДА В БИТВЕ", startNewBattle: "НОВАЯ БИТВА", quitBattle: "Покинуть битву?", quitWarning: "Ваш прогресс будет утерян. Вы уверены, что хотите выйти?", yesQuit: "ДА, ВЫЙТИ", cancel: "ОТМЕНА", run: "ЗАПУСК", testing: "ТЕСТИРОВАНИЕ...", runAllTests: "ЗАПУСТИТЬ ВСЕ ТЕСТЫ", runExample: "Запустить пример", addToStdin: "Добавить в Stdin", examples: "Примеры", solvedProblems: "Решено задач", winRate: "Процент побед", currentStreak: "Текущая серия", battlesFought: "Всего битв", battlesWon: "Побед", rank: "Ранг", timeTaken: "Затраченное время", langUsed: "Язык", squire: "Оруженосец", knight: "Рыцарь", grandmaster: "Гроссмейстер", peasant: "Начинающий крестьянин",
  },
  hu: {
    battle: "Csata", contests: "Versenyek", discuss: "Diskurzus", friends: "Barátok", settings: "Beállítások", editor: "Szerkesztő", problem: "Feladat", profile: "Profil", admin: "Dev Funkciók", signIn: "Bejelentkezés", signOut: "Kijelentkezés", exitGuest: "Vendég mód elhagyása", profileOverview: "Profil áttekintése", configureProfile: "Profil szerkesztése", colorThemes: "Szín témák", fontFamily: "Betűtípus", textSize: "Szövegméret", keybindings: "Billentyűkombinációk", language: "Interfész nyelve", arenaRules: "Aréna szabályok", whyJoin: "Miért csatlakozz?", authRequired: "Bejelentkezés szükséges", playAsGuest: "Játék vendégként", startQuickBattle: "GYORS CSATA INDÍTÁSA", availableChallenges: "Elérhető kihívások", battleVictorious: "GYŐZELMES CSATA", startNewBattle: "ÚJ CSATA INDÍTÁSA", quitBattle: "Kilépsz a csatából?", quitWarning: "A haladásod elvész. Biztosan ki akarsz lépni?", yesQuit: "IGEN, KILÉPÉS", cancel: "MÉGSE", run: "FUTTATÁS", testing: "TESZTELÉS...", runAllTests: "ÖSSZES TESZT FUTTATÁSA", runExample: "Példa futtatása", addToStdin: "Hozzáadás a Stdin-hez", examples: "Példák", solvedProblems: "Megoldott feladatok", winRate: "Győzelmi arány", currentStreak: "Jelenlegi sorozat", battlesFought: "Megvívott csaták", battlesWon: "Megnyert csaták", rank: "Rang", timeTaken: "Eltelt idő", langUsed: "Nyelv", squire: "Fegyverhordozó", knight: "Lovag", grandmaster: "Nagymester", peasant: "Kezdő paraszt",
  },
  es: {
    battle: "Batalla", contests: "Concursos", discuss: "Discusión", friends: "Amigos", settings: "Ajustes", editor: "Editor", problem: "Problema", profile: "Perfil", admin: "Opciones Dev", signIn: "Iniciar sesión", signOut: "Cerrar sesión", exitGuest: "Salir de Invitado", profileOverview: "Vista general", configureProfile: "Configurar perfil", colorThemes: "Temas de color", fontFamily: "Fuente", textSize: "Tamaño de texto", keybindings: "Atajos", language: "Idioma de interfaz", arenaRules: "Reglas de arena", whyJoin: "¿Por qué unirse?", authRequired: "Autenticación requerida", playAsGuest: "Jugar como invitado", startQuickBattle: "INICIAR BATALLA RÁPIDA", availableChallenges: "Desafíos disponibles", battleVictorious: "BATALLA VICTORIOSA", startNewBattle: "NUEVA BATALLA", quitBattle: "¿Salir de la batalla?", quitWarning: "Tu progreso se perderá. ¿Estás seguro de que quieres salir?", yesQuit: "SÍ, SALIR", cancel: "CANCELAR", run: "EJECUTAR", testing: "PROBANDO...", runAllTests: "LANZAR TODOS LOS TESTS", runExample: "Ejecutar <example></example>", addToStdin: "Añadir a Stdin", examples: "Ejemplos", solvedProblems: "Problemas resueltos", winRate: "Tasa de victoria", currentStreak: "Racha actual", battlesFought: "Batallas luchadas", battlesWon: "Batallas ganadas", rank: "Rango", timeTaken: "Tiempo tomado", langUsed: "Lenguaje", squire: "Escudero", knight: "Caballero", grandmaster: "Gran Maestro", peasant: "Campesino principiante",
  },
  it: {
    battle: "Battaglia", contests: "Concorsi", discuss: "Discussione", friends: "Amici", settings: "Impostazioni", editor: "Editor", problem: "Problema", profile: "Profilo", admin: "Opzioni Dev", signIn: "Accedi", signOut: "Esci", exitGuest: "Esci da Ospite", profileOverview: "Panoramica profilo", configureProfile: "Configura profilo", colorThemes: "Temi colore", fontFamily: "Carattere", textSize: "Dimensione testo", keybindings: "Scorciatoie", language: "Lingua interfaccia", arenaRules: "Regole arena", whyJoin: "Perché unirsi?", authRequired: "Autenticazione richiesta", playAsGuest: "Gioca come ospite", startQuickBattle: "INIZIA BATTAGLIA RAPIDA", availableChallenges: "Sfide disponibili", battleVictorious: "BATTAGLIA VINTA", startNewBattle: "NUOVA BATTAGLIA", quitBattle: "Abbandonare la battaglia?", quitWarning: "I tuoi progressi andranno persi. Sei sicuro di voler uscire?", yesQuit: "SÌ, ESCI", cancel: "ANNULLA", run: "ESEGUI", testing: "TEST IN CORSO...", runAllTests: "ESEGUI TUTTI I TEST", runExample: "Esegui esempio", addToStdin: "Aggiungi a Stdin", examples: "Esempi", solvedProblems: "Problemi risolti", winRate: "Percentuale vittorie", currentStreak: "Serie attuale", battlesFought: "Battaglie combattute", battlesWon: "Battaglie vinte", rank: "Grado", timeTaken: "Tempo impiegato", langUsed: "Linguaggio", squire: "Scudiero", knight: "Cavaliere", grandmaster: "Gran Maestro", peasant: "Contadino principiante",
  },
  zh: {
    battle: "战斗", contests: "竞赛", discuss: "讨论", friends: "好友", settings: "设置", editor: "编辑器", problem: "题目", profile: "个人资料", admin: "开发者选项", signIn: "登录", signOut: "退出", exitGuest: "退出访客模式", profileOverview: "个人概览", configureProfile: "设置资料", colorThemes: "颜色主题", fontFamily: "字体", textSize: "文字大小", keybindings: "键位绑定", language: "界面语言", arenaRules: "竞技场规则", whyJoin: "为什么要加入？", authRequired: "需要身份验证", playAsGuest: "以访客身份游玩", startQuickBattle: "开始快速战斗", availableChallenges: "可用挑战", battleVictorious: "战斗获胜", startNewBattle: "开始新战斗", quitBattle: "退出战斗？", quitWarning: "您的进度将会丢失。确定要退出吗？", yesQuit: "是的，退出", cancel: "取消", run: "运行", testing: "测试中...", runAllTests: "运行所有测试", runExample: "运行示例", addToStdin: "添加到输入", examples: "示例", solvedProblems: "已解决题目", winRate: "胜率", currentStreak: "当前连胜", battlesFought: "战斗总数", battlesWon: "胜场数", rank: "等级", timeTaken: "用时", langUsed: "语言", squire: "侍从", knight: "骑士", grandmaster: "宗师", peasant: "新手农民",
  },
  ja: {
    battle: "バトル", contests: "コンテスト", discuss: "ディスカッション", friends: "フレンド", settings: "設定", editor: "エディタ", problem: "問題", profile: "プロフィール", admin: "開発者ツール", signIn: "サインイン", signOut: "サインアウト", exitGuest: "ゲストを終了", profileOverview: "プロフィール概要", configureProfile: "プロフィール設定", colorThemes: "カラーテーマ", fontFamily: "フォント", textSize: "テキストサイズ", keybindings: "キーバインド", language: "インターフェース言語", arenaRules: "アリーナルール", whyJoin: "参加する理由", authRequired: "認証が必要です", playAsGuest: "ゲストとしてプレイ", startQuickBattle: "クイックバトル開始", availableChallenges: "利用可能なチャレンジ", battleVictorious: "勝利！", startNewBattle: "新しいバトルを開始", quitBattle: "バトルを終了しますか？", quitWarning: "進捗が失われます。本当に終了しますか？", yesQuit: "はい、終了します", cancel: "キャンセル", run: "実行", testing: "テスト中...", runAllTests: "すべてのテストを実行", runExample: "サンプルを実行", addToStdin: "Stdinに追加", examples: "サンプル", solvedProblems: "解決済みの問題", winRate: "勝率", currentStreak: "現在のストリーク", battlesFought: "対戦数", battlesWon: "勝利数", rank: "ランク", timeTaken: "かかった時間", langUsed: "言語", squire: "従騎士", knight: "騎士", grandmaster: "グランドマスター", peasant: "見習い農民",
  }
};

export type TranslationKey = keyof typeof TRANSLATIONS.en;
export type SupportedLanguage = keyof typeof TRANSLATIONS;
