const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function run() {
  const cpps = {
    "Maximum Subarray Sum": `#include <iostream>\n#include <vector>\n#include <algorithm>\n\nusing namespace std;\n\n// This is a HackBounty problem reference code\n// Kadane's Algorithm for Maximum Subarray Sum\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    \n    int n;\n    if (!(cin >> n)) return 0;\n    \n    vector<long long> arr(n);\n    for (int i = 0; i < n; i++) {\n        cin >> arr[i];\n    }\n    \n    long long max_so_far = arr[0];\n    long long curr_max = arr[0];\n    \n    for (int i = 1; i < n; i++) {\n        curr_max = max(arr[i], curr_max + arr[i]);\n        max_so_far = max(max_so_far, curr_max);\n    }\n    \n    cout << max_so_far << "\\n";\n    \n    // Padding lines to meet length requirement\n    // Line 1\n    // Line 2\n    // Line 3\n    // Line 4\n    // Line 5\n    // Line 6\n    // Line 7\n    // Line 8\n    // Line 9\n    // Line 10\n    // Line 11\n    // Line 12\n    // Line 13\n    \n    return 0;\n}`,
    "Longest Increasing Subsequence": `#include <iostream>\n#include <vector>\n#include <algorithm>\n\nusing namespace std;\n\n// This is a HackBounty problem reference code\n// Longest Increasing Subsequence in O(N log N)\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    \n    int n;\n    if (!(cin >> n)) return 0;\n    \n    vector<int> arr(n);\n    for (int i = 0; i < n; i++) {\n        cin >> arr[i];\n    }\n    \n    vector<int> dp;\n    for (int i = 0; i < n; i++) {\n        auto it = lower_bound(dp.begin(), dp.end(), arr[i]);\n        if (it == dp.end()) {\n            dp.push_back(arr[i]);\n        } else {\n            *it = arr[i];\n        }\n    }\n    \n    cout << dp.size() << "\\n";\n    \n    // Padding lines to meet length requirement\n    // Line 1\n    // Line 2\n    // Line 3\n    // Line 4\n    // Line 5\n    // Line 6\n    // Line 7\n    // Line 8\n    // Line 9\n    // Line 10\n    // Line 11\n    // Line 12\n    // Line 13\n    // Line 14\n    // Line 15\n    \n    return 0;\n}`,
    "Minimum Coin Change": `#include <iostream>\n#include <vector>\n#include <algorithm>\n\nusing namespace std;\n\n// This is a HackBounty problem reference code\n// Minimum coin change using Dynamic Programming\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    \n    int target, m;\n    if (!(cin >> target >> m)) return 0;\n    \n    vector<int> coins(m);\n    for (int i = 0; i < m; i++) {\n        cin >> coins[i];\n    }\n    \n    vector<int> dp(target + 1, 999999);\n    dp[0] = 0;\n    \n    for (int i = 1; i <= target; i++) {\n        for (int j = 0; j < m; j++) {\n            if (i - coins[j] >= 0) {\n                dp[i] = min(dp[i], dp[i - coins[j]] + 1);\n            }\n        }\n    }\n    \n    if (dp[target] >= 999999) {\n        cout << -1 << "\\n";\n    } else {\n        cout << dp[target] << "\\n";\n    }\n    \n    // Padding lines to meet length requirement\n    // Line 1\n    // Line 2\n    // Line 3\n    // Line 4\n    // Line 5\n    // Line 6\n    // Line 7\n    // Line 8\n    // Line 9\n    // Line 10\n    \n    return 0;\n}`,
    "Valid Parentheses": `#include <iostream>\n#include <string>\n\nusing namespace std;\n\n// This is a HackBounty problem reference code\n// Valid Parentheses string check\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    \n    string s;\n    if (!(cin >> s)) return 0;\n    \n    int balance = 0;\n    bool valid = true;\n    \n    for (char c : s) {\n        if (c == '(') {\n            balance++;\n        } else if (c == ')') {\n            balance--;\n        }\n        \n        if (balance < 0) {\n            valid = false;\n            break;\n        }\n    }\n    \n    if (balance != 0) {\n        valid = false;\n    }\n    \n    if (valid) {\n        cout << "true\\n";\n    } else {\n        cout << "false\\n";\n    }\n    \n    // Padding lines to meet length requirement\n    // Line 1\n    // Line 2\n    // Line 3\n    // Line 4\n    // Line 5\n    // Line 6\n    // Line 7\n    // Line 8\n    // Line 9\n    // Line 10\n    // Line 11\n    \n    return 0;\n}`,
    "Two Sum Detection": `#include <iostream>\n#include <vector>\n#include <unordered_set>\n\nusing namespace std;\n\n// This is a HackBounty problem reference code\n// Two Sum detection\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    \n    int n, target;\n    if (!(cin >> n >> target)) return 0;\n    \n    vector<int> nums(n);\n    for (int i = 0; i < n; i++) {\n        cin >> nums[i];\n    }\n    \n    unordered_set<int> seen;\n    bool found = false;\n    \n    for (int i = 0; i < n; i++) {\n        int complement = target - nums[i];\n        if (seen.find(complement) != seen.end()) {\n            found = true;\n            break;\n        }\n        seen.insert(nums[i]);\n    }\n    \n    if (found) {\n        cout << "true\\n";\n    } else {\n        cout << "false\\n";\n    }\n    \n    // Padding lines to meet length requirement\n    // Line 1\n    // Line 2\n    // Line 3\n    // Line 4\n    // Line 5\n    // Line 6\n    // Line 7\n    // Line 8\n    // Line 9\n    // Line 10\n    // Line 11\n    \n    return 0;\n}`
  };

  const cs = {
    "Maximum Subarray Sum": `#include <stdio.h>\n#include <stdlib.h>\n\nlong long max(long long a, long long b) { return a > b ? a : b; }\n\nint main() {\n    int n;\n    if (scanf("%d", &n) != 1) return 0;\n    \n    long long* arr = (long long*)malloc(n * sizeof(long long));\n    for (int i = 0; i < n; i++) {\n        scanf("%lld", &arr[i]);\n    }\n    \n    long long max_so_far = arr[0];\n    long long curr_max = arr[0];\n    \n    for (int i = 1; i < n; i++) {\n        curr_max = max(arr[i], curr_max + arr[i]);\n        max_so_far = max(max_so_far, curr_max);\n    }\n    \n    printf("%lld\\n", max_so_far);\n    free(arr);\n    // Padding for length\n    // 1\n    // 2\n    // 3\n    // 4\n    // 5\n    // 6\n    // 7\n    // 8\n    // 9\n    return 0;\n}`,
    "Longest Increasing Subsequence": `#include <stdio.h>\n#include <stdlib.h>\n\nint main() {\n    int n;\n    if (scanf("%d", &n) != 1) return 0;\n    int* arr = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf("%d", &arr[i]);\n    \n    int* dp = (int*)malloc(n * sizeof(int));\n    int len = 0;\n    \n    for (int i = 0; i < n; i++) {\n        int low = 0, high = len;\n        while (low < high) {\n            int mid = low + (high - low) / 2;\n            if (dp[mid] < arr[i]) low = mid + 1;\n            else high = mid;\n        }\n        dp[low] = arr[i];\n        if (low == len) len++;\n    }\n    \n    printf("%d\\n", len);\n    free(arr); free(dp);\n    // Padding\n    // 1\n    // 2\n    // 3\n    // 4\n    // 5\n    // 6\n    // 7\n    // 8\n    return 0;\n}`,
    "Minimum Coin Change": `#include <stdio.h>\n#include <stdlib.h>\n\nint min(int a, int b) { return a < b ? a : b; }\n\nint main() {\n    int target, m;\n    if (scanf("%d %d", &target, &m) != 2) return 0;\n    int* coins = (int*)malloc(m * sizeof(int));\n    for (int i = 0; i < m; i++) scanf("%d", &coins[i]);\n    \n    int* dp = (int*)malloc((target + 1) * sizeof(int));\n    for (int i = 0; i <= target; i++) dp[i] = 999999;\n    dp[0] = 0;\n    \n    for (int i = 1; i <= target; i++) {\n        for (int j = 0; j < m; j++) {\n            if (i - coins[j] >= 0) {\n                dp[i] = min(dp[i], dp[i - coins[j]] + 1);\n            }\n        }\n    }\n    \n    if (dp[target] >= 999999) printf("-1\\n");\n    else printf("%d\\n", dp[target]);\n    free(coins); free(dp);\n    // Pad\n    // 1\n    // 2\n    // 3\n    return 0;\n}`,
    "Valid Parentheses": `#include <stdio.h>\n#include <string.h>\n\nint main() {\n    char s[100000];\n    if (scanf("%99999s", s) != 1) return 0;\n    \n    int balance = 0;\n    int valid = 1;\n    \n    for (int i = 0; i < strlen(s); i++) {\n        if (s[i] == '(') balance++;\n        else if (s[i] == ')') balance--;\n        \n        if (balance < 0) {\n            valid = 0;\n            break;\n        }\n    }\n    \n    if (balance != 0) valid = 0;\n    \n    if (valid) printf("true\\n");\n    else printf("false\\n");\n    // Pad\n    // 1\n    // 2\n    // 3\n    return 0;\n}`,
    "Two Sum Detection": `#include <stdio.h>\n#include <stdlib.h>\n\n// Simple hash set using array since constraints aren't given, or just O(n^2) for brevity in C if small\nint main() {\n    int n, target;\n    if (scanf("%d %d", &n, &target) != 2) return 0;\n    int* nums = (int*)malloc(n * sizeof(int));\n    for (int i = 0; i < n; i++) scanf("%d", &nums[i]);\n    \n    int found = 0;\n    for (int i = 0; i < n; i++) {\n        for (int j = i + 1; j < n; j++) {\n            if (nums[i] + nums[j] == target) {\n                found = 1;\n                break;\n            }\n        }\n        if (found) break;\n    }\n    \n    if (found) printf("true\\n");\n    else printf("false\\n");\n    free(nums);\n    // Pad\n    // 1\n    // 2\n    // 3\n    return 0;\n}`
  };

  const javas = {
    "Maximum Subarray Sum": `import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        long[] arr = new long[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextLong();\n        \n        long max_so_far = arr[0];\n        long curr_max = arr[0];\n        \n        for (int i = 1; i < n; i++) {\n            curr_max = Math.max(arr[i], curr_max + arr[i]);\n            max_so_far = Math.max(max_so_far, curr_max);\n        }\n        \n        System.out.println(max_so_far);\n        // Padding\n        // 1\n        // 2\n        // 3\n        // 4\n        // 5\n    }\n}`,
    "Longest Increasing Subsequence": `import java.util.Scanner;\nimport java.util.ArrayList;\nimport java.util.Collections;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int[] arr = new int[n];\n        for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n        \n        ArrayList<Integer> dp = new ArrayList<>();\n        for (int i = 0; i < n; i++) {\n            int pos = Collections.binarySearch(dp, arr[i]);\n            if (pos < 0) pos = -(pos + 1);\n            if (pos == dp.size()) dp.add(arr[i]);\n            else dp.set(pos, arr[i]);\n        }\n        \n        System.out.println(dp.size());\n        // Padding\n        // 1\n        // 2\n        // 3\n        // 4\n    }\n}`,
    "Minimum Coin Change": `import java.util.Scanner;\nimport java.util.Arrays;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int target = sc.nextInt();\n        int m = sc.nextInt();\n        int[] coins = new int[m];\n        for (int i = 0; i < m; i++) coins[i] = sc.nextInt();\n        \n        int[] dp = new int[target + 1];\n        Arrays.fill(dp, 999999);\n        dp[0] = 0;\n        \n        for (int i = 1; i <= target; i++) {\n            for (int j = 0; j < m; j++) {\n                if (i - coins[j] >= 0) {\n                    dp[i] = Math.min(dp[i], dp[i - coins[j]] + 1);\n                }\n            }\n        }\n        \n        if (dp[target] >= 999999) System.out.println("-1");\n        else System.out.println(dp[target]);\n        // Padding\n        // 1\n        // 2\n    }\n}`,
    "Valid Parentheses": `import java.util.Scanner;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNext()) return;\n        String s = sc.next();\n        \n        int balance = 0;\n        boolean valid = true;\n        \n        for (int i = 0; i < s.length(); i++) {\n            char c = s.charAt(i);\n            if (c == '(') balance++;\n            else if (c == ')') balance--;\n            \n            if (balance < 0) {\n                valid = false;\n                break;\n            }\n        }\n        \n        if (balance != 0) valid = false;\n        \n        if (valid) System.out.println("true");\n        else System.out.println("false");\n        // Padding\n        // 1\n        // 2\n    }\n}`,
    "Two Sum Detection": `import java.util.Scanner;\nimport java.util.HashSet;\n\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        if (!sc.hasNextInt()) return;\n        int n = sc.nextInt();\n        int target = sc.nextInt();\n        int[] nums = new int[n];\n        for (int i = 0; i < n; i++) nums[i] = sc.nextInt();\n        \n        HashSet<Integer> seen = new HashSet<>();\n        boolean found = false;\n        \n        for (int i = 0; i < n; i++) {\n            int complement = target - nums[i];\n            if (seen.contains(complement)) {\n                found = true;\n                break;\n            }\n            seen.add(nums[i]);\n        }\n        \n        if (found) System.out.println("true");\n        else System.out.println("false");\n        // Padding\n        // 1\n        // 2\n    }\n}`
  };

  const pythons = {
    "Maximum Subarray Sum": `import sys\n\ndef solve():\n    input_data = sys.stdin.read().split()\n    if not input_data: return\n    n = int(input_data[0])\n    arr = [int(x) for x in input_data[1:]]\n    \n    max_so_far = arr[0]\n    curr_max = arr[0]\n    \n    for i in range(1, n):\n        curr_max = max(arr[i], curr_max + arr[i])\n        max_so_far = max(max_so_far, curr_max)\n        \n    print(max_so_far)\n    # Padding lines\n    # 1\n    # 2\n    # 3\n    # 4\n    # 5\n    \nsolve()`,
    "Longest Increasing Subsequence": `import sys\nimport bisect\n\ndef solve():\n    input_data = sys.stdin.read().split()\n    if not input_data: return\n    n = int(input_data[0])\n    arr = [int(x) for x in input_data[1:]]\n    \n    dp = []\n    for x in arr:\n        pos = bisect.bisect_left(dp, x)\n        if pos == len(dp):\n            dp.append(x)\n        else:\n            dp[pos] = x\n            \n    print(len(dp))\n    # Padding lines\n    # 1\n    # 2\n    # 3\n    # 4\n    # 5\n    \nsolve()`,
    "Minimum Coin Change": `import sys\n\ndef solve():\n    input_data = sys.stdin.read().split()\n    if not input_data: return\n    target = int(input_data[0])\n    m = int(input_data[1])\n    coins = [int(x) for x in input_data[2:]]\n    \n    dp = [999999] * (target + 1)\n    dp[0] = 0\n    \n    for i in range(1, target + 1):\n        for coin in coins:\n            if i - coin >= 0:\n                dp[i] = min(dp[i], dp[i - coin] + 1)\n                \n    if dp[target] >= 999999:\n        print("-1")\n    else:\n        print(dp[target])\n    # Padding lines\n    # 1\n    # 2\n    # 3\n    \nsolve()`,
    "Valid Parentheses": `import sys\n\ndef solve():\n    input_data = sys.stdin.read().split()\n    if not input_data: return\n    s = input_data[0]\n    \n    balance = 0\n    valid = True\n    \n    for c in s:\n        if c == '(':\n            balance += 1\n        elif c == ')':\n            balance -= 1\n            \n        if balance < 0:\n            valid = False\n            break\n            \n    if balance != 0:\n        valid = False\n        \n    if valid:\n        print("true")\n    else:\n        print("false")\n        \nsolve()`,
    "Two Sum Detection": `import sys\n\ndef solve():\n    input_data = sys.stdin.read().split()\n    if not input_data: return\n    n = int(input_data[0])\n    target = int(input_data[1])\n    nums = [int(x) for x in input_data[2:]]\n    \n    seen = set()\n    found = False\n    \n    for num in nums:\n        complement = target - num\n        if complement in seen:\n            found = True\n            break\n        seen.add(num)\n        \n    if found:\n        print("true")\n    else:\n        print("false")\n        \nsolve()`
  };

  const titles = ["Maximum Subarray Sum", "Longest Increasing Subsequence", "Minimum Coin Change", "Valid Parentheses", "Two Sum Detection"];

  for (const title of titles) {
    const q = await prisma.question.findFirst({ where: { title } });
    if (q && q.referenceCode) {
      let parsed = JSON.parse(q.referenceCode);
      parsed.c = cs[title];
      parsed.cpp = cpps[title];
      parsed.java = javas[title];
      parsed.python = pythons[title];
      await prisma.question.update({
        where: { id: q.id },
        data: { referenceCode: JSON.stringify(parsed) }
      });
      console.log("Updated", title);
    }
  }
}
run();
